"use client";

import React from "react";
import { TouchpointMetric, SentimentBreakdown } from "@/lib/analytics/analytics-service";
import { Bot, Mail, MessageSquare, CheckCircle2, Calendar, Smile, ShieldAlert } from "lucide-react";
import { cn } from "@/lib/utils";

interface CadenceAnalyticsProps {
  touchpoints: TouchpointMetric[];
  sentiment: SentimentBreakdown[];
}

export function CadenceAnalytics({ touchpoints, sentiment }: CadenceAnalyticsProps) {
  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
      {/* Touchpoint Conversion Waterfall */}
      <div className="bg-white rounded-2xl border border-border/80 p-4 sm:p-6 shadow-card space-y-5">
        <div>
          <div className="flex items-center gap-2">
            <span className="w-2.5 h-2.5 rounded-full bg-purple-500" />
            <h3 className="font-medium text-sm text-text-primary flex items-center gap-1.5">
              <Bot className="w-4 h-4 text-purple-600" />
              Autonomous Cadence Touchpoint Yield
            </h3>
          </div>
          <p className="text-xs text-text-secondary mt-0.5">
            Reply distribution and discovery calls generated across follow-up steps
          </p>
        </div>

        <div className="space-y-3">
          {touchpoints.map((t) => (
            <div
              key={t.touch}
              className="p-3.5 rounded-xl border border-border/70 bg-surface-raised/40 hover:bg-surface-raised/70 transition-colors space-y-2"
            >
              <div className="flex items-center justify-between text-xs">
                <div className="flex items-center gap-2">
                  <span className="w-5 h-5 rounded-md bg-indigo-50 border border-indigo-200 text-indigo-700 font-mono text-[11px] font-bold flex items-center justify-center">
                    T{t.touch}
                  </span>
                  <span className="font-medium text-text-primary">{t.name}</span>
                </div>
                <span className="font-mono text-xs font-bold text-emerald-700 bg-emerald-50 border border-emerald-200 px-2 py-0.5 rounded-md">
                  {t.replyRate}% Reply Rate
                </span>
              </div>

              <div className="grid grid-cols-3 gap-2 pt-1 border-t border-border/50 text-[11px] font-mono">
                <div>
                  <span className="text-text-secondary block text-[10px]">Dispatched</span>
                  <span className="font-semibold text-text-primary">{t.dispatched}</span>
                </div>
                <div>
                  <span className="text-text-secondary block text-[10px]">Replies Received</span>
                  <span className="font-semibold text-text-primary">{t.replies}</span>
                </div>
                <div>
                  <span className="text-text-secondary block text-[10px]">Meetings Won</span>
                  <span className="font-semibold text-emerald-700 flex items-center gap-1">
                    <Calendar className="w-3 h-3 text-emerald-600" />
                    {t.meetingsGenerated}
                  </span>
                </div>
              </div>
            </div>
          ))}
        </div>

        <div className="p-3 rounded-xl bg-indigo-50/70 border border-indigo-200 text-xs text-indigo-900 flex items-start gap-2">
          <Bot className="w-4 h-4 text-indigo-600 shrink-0 mt-0.5" />
          <p className="text-[11px] text-indigo-900/90 leading-relaxed">
            <strong>Key Insight:</strong> 52% of discovery calls were generated by <strong>Touch 2 (Follow-Up)</strong>. 
            Automated persistence nearly doubles pipeline conversion over single cold pitches.
          </p>
        </div>
      </div>

      {/* Inbound Reply Sentiment Breakdown */}
      <div className="bg-white rounded-2xl border border-border/80 p-4 sm:p-6 shadow-card space-y-5">
        <div>
          <div className="flex items-center gap-2">
            <span className="w-2.5 h-2.5 rounded-full bg-emerald-500" />
            <h3 className="font-medium text-sm text-text-primary flex items-center gap-1.5">
              <Smile className="w-4 h-4 text-emerald-600" />
              Inbound Reply Intent Breakdown
            </h3>
          </div>
          <p className="text-xs text-text-secondary mt-0.5">
            Classification of inbound replies processed by Claude 3.5 Sonnet
          </p>
        </div>

        {/* Stacked percentage bar */}
        <div className="space-y-1.5">
          <div className="h-4 w-full rounded-full overflow-hidden flex p-0.5 bg-slate-100 border border-slate-200/80">
            {sentiment.map((item, idx) => (
              <div
                key={idx}
                style={{
                  width: `${item.percentage}%`,
                  backgroundColor: item.color,
                }}
                className="h-full first:rounded-l-full last:rounded-r-full transition-all duration-300"
                title={`${item.intent}: ${item.percentage}%`}
              />
            ))}
          </div>
          <div className="flex items-center justify-between text-[10px] font-mono text-text-secondary">
            <span>Positive / Qualified (84.1%)</span>
            <span>Neutral / Opt-Out (15.9%)</span>
          </div>
        </div>

        {/* Sentiment cards list */}
        <div className="space-y-2 pt-2">
          {sentiment.map((item, idx) => (
            <div
              key={idx}
              className="flex items-center justify-between p-2.5 rounded-xl border border-border/70 bg-surface hover:bg-surface-raised/50 transition-colors text-xs"
            >
              <div className="flex items-center gap-2">
                <span
                  className="w-2.5 h-2.5 rounded-full shrink-0"
                  style={{ backgroundColor: item.color }}
                />
                <span className="font-medium text-text-primary">{item.intent}</span>
              </div>

              <div className="flex items-center gap-3 font-mono">
                <span className="text-text-secondary text-[11px]">{item.count} replies</span>
                <span className="font-bold text-text-primary">{item.percentage}%</span>
              </div>
            </div>
          ))}
        </div>

        <div className="p-3 rounded-xl bg-emerald-50/70 border border-emerald-200 text-xs text-emerald-900 flex items-start gap-2">
          <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0 mt-0.5" />
          <p className="text-[11px] text-emerald-900/90 leading-relaxed">
            Over <strong>84%</strong> of inbound responses are actionable inquiries or project discovery requests, 
            confirming high ICP relevance and strong value proposition targeting.
          </p>
        </div>
      </div>
    </div>
  );
}
